// Rich "expansion" content for hotspots that get the full modal treatment
// (intro + flip-card sections), rather than the simple bottom-drawer list.
//
// GENERATED by scripts/sync_notion.py -- do not hand-edit past the header;
// re-run `python3 scripts/sync_notion.py --write` to refresh from Notion.

export interface Subject {
  /** Path (e.g. /photos/foo.jpg) or URL. Omit to show a placeholder tile. */
  photo?: string;
  /** One line describing the photo. */
  caption: string;
  /** Optional -- makes the caption a link (opens in a new tab). */
  link?: string;
}

export interface ExpansionSection {
  id: string;
  label: string;
  /** Max 3 -- the flipped card shows these as a small grid. */
  subjects: Subject[];
}

export interface HotspotExpansion {
  hotspotId: string;
  /** A couple of sentences, shown above the sections. */
  intro: string;
  sections: ExpansionSection[];
}

export const hotspotExpansions: HotspotExpansion[] = [
  {
    hotspotId: "espresso",
    intro: "Placeholder intro -- replace with 1-2 real sentences about espresso.",
    sections: [
      {
        id: "beans",
        label: "Beans",
        subjects: [
        { caption: "CoRo: Morgan\u2019s Blend [Berkeley, CA]", link: "https://www.corocoffeeroom.com/corocoffeebrand/coro-morgans-blend", photo: "/coffee-beans-morgans-blend.jpeg" },
        { caption: "Black and White Coffee Roasters: Hambela Natural (EA Decaf) [Raleigh, NC]", link: "https://www.blackwhiteroasters.com/collections/all-coffee", photo: "/coffee-beans-black-and-white-decaf.jpeg" },
        { caption: "Moonwake: granja pariso 92 thermal shock caturra [San Jose, CA]", link: "https://moonwakecoffeeroasters.com/products/granja-paraiso-92-thermal-shock-caturra-colombia", photo: "/coffee-beans-moonwake-granja-pariso-92.jpeg" },
        ],
      },
      {
        id: "cafes",
        label: "Cafes",
        subjects: [
        { caption: "SEY: pour overs [Bushwick]" },
        { caption: "The Mandarin: latte, flavored lattes [Two Bridges]" },
        { caption: "No Stress: latte [Long Island City]" },
        ],
      },
      {
        id: "matcha",
        label: "Matcha",
        subjects: [
        { caption: "Kijitora [Williamsburg]" },
        { caption: "Verse [Astoria]" },
        { caption: "Rok [West Village]" },
        ],
      },
    ],
  },
  {
    hotspotId: "wine-fridge",
    intro: "Placeholder intro -- replace with 1-2 real sentences about wine fridge.",
    sections: [
      {
        id: "red",
        label: "Red",
        subjects: [
        { caption: "Kosta Browne: Pinot Noir 2021 [Russian River Valley, CA]", photo: "/wine-red-kosta-browne.jpeg" },
        { caption: "Austin Hope: Cabernet Sauvignon [Paso Robles, CA]", photo: "/wine-red-austin-hope.jpeg" },
        { caption: "Tenuta San Guido: Sassicaia 2019 [Tuscany, Italy]", photo: "/wine-red-sassicaia.jpeg" },
        ],
      },
      {
        id: "white",
        label: "White",
        subjects: [
        { caption: "Willi Schaefer: Graacher Domprobst Riesling Kabinett 2024 [Mosel, Germany]", photo: "/wine-white-willi-schaefer.jpeg" },
        { caption: "Susana Balbo: CRIOS Torrontes 2023 [Uco Valley, Argentina]", photo: "/wine-white-crios.jpeg" },
        { caption: "Nieport Wine: Redoma Branco Revera 2024 [Douro, Portugal]", photo: "/wine-white-nieport.jpeg" },
        ],
      },
      {
        id: "wine-bars",
        label: "Wine Bars",
        subjects: [
        { caption: "Stars [East Village, NYC]" },
        { caption: "Sauced [Williamsburg & Lower East Side, NYC]" },
        ],
      },
    ],
  },
];

export function getExpansion(hotspotId: string): HotspotExpansion | undefined {
  return hotspotExpansions.find((e) => e.hotspotId === hotspotId);
}
