// Rich "expansion" content for hotspots that get the full modal treatment
// (intro + flip-card sections), rather than the simple bottom-drawer list.
//
// GENERATED by scripts/sync_notion.py -- do not hand-edit past the header;
// re-run `python3 scripts/sync_notion.py --write` to refresh from Notion.

export interface Subject {
  /** Path (e.g. /photos/foo.jpg) or URL. Omit to show a placeholder tile. */
  photo?: string;
  /** One line describing the photo. */
  caption: string;
  /** Optional -- makes the caption a link (opens in a new tab). */
  link?: string;
}

export interface ExpansionSection {
  id: string;
  label: string;
  /** Max 3 -- the flipped card shows these as a small grid. */
  subjects: Subject[];
}

export interface HotspotExpansion {
  hotspotId: string;
  /** A couple of sentences, shown above the sections. */
  intro: string;
  sections: ExpansionSection[];
}

export const hotspotExpansions: HotspotExpansion[] = [
  {
    hotspotId: "espresso",
    intro: "Placeholder intro -- replace with 1-2 real sentences about espresso.",
    sections: [
      {
        id: "beans",
        label: "Beans",
        subjects: [
        { caption: "CoRo: Morgan\u2019s Blend [Berkeley, CA]", link: "https://www.corocoffeeroom.com/corocoffeebrand/coro-morgans-blend", photo: "/coffee-beans-morgans-blend.jpeg" },
        { caption: "Black and White Coffee Roasters: Hambela Natural (EA Decaf) [Raleigh, NC]", link: "https://www.blackwhiteroasters.com/collections/all-coffee", photo: "/coffee-beans-black-and-white-decaf.jpeg" },
        { caption: "Moonwake: granja pariso 92 thermal shock caturra [San Jose, CA]", link: "https://moonwakecoffeeroasters.com/products/granja-paraiso-92-thermal-shock-caturra-colombia", photo: "/coffee-beans-moonwake-granja-pariso-92.jpeg" },
        ],
      },
      {
        id: "cafes",
        label: "Cafes",
        subjects: [
        { caption: "SEY: pour overs [Bushwick]" },
        { caption: "The Mandarin: latte, flavored lattes [Two Bridges]" },
        { caption: "No Stress: latte [Long Island City]" },
        ],
      },
      {
        id: "matcha",
        label: "Matcha",
        subjects: [
        { caption: "Kijitora [Williamsburg]" },
        { caption: "Verse [Astoria]" },
        { caption: "Rok [West Village]" },
        ],
      },
    ],
  },
  {
    hotspotId: "wine-fridge",
    intro: "Placeholder intro -- replace with 1-2 real sentences about wine fridge.",
    sections: [
      {
        id: "red",
        label: "Red",
        subjects: [
        { caption: "Kosta Browne: Pinot Noir 2021 [Russian River Valley, CA]", photo: "/wine-red-kosta-browne.jpeg" },
        { caption: "Austin Hope: Cabernet Sauvignon [Paso Robles, CA]", photo: "/wine-red-austin-hope.jpeg" },
        { caption: "Tenuta San Guido: Sassicaia 2019 [Tuscany, Italy]", photo: "/wine-red-sassicaia.jpeg" },
        ],
      },
      {
        id: "white",
        label: "White",
        subjects: [
        { caption: "Willi Schaefer: Graacher Domprobst Riesling Kabinett 2024 [Mosel, Germany]", photo: "/wine-white-willi-schaefer.jpeg" },
        { caption: "Susana Balbo: CRIOS Torrontes 2023 [Uco Valley, Argentina]", photo: "/wine-white-crios.jpeg" },
        { caption: "Nieport Wine: Redoma Branco Revera 2024 [Douro, Portugal]", photo: "/wine-white-nieport.jpeg" },
        ],
      },
      {
        id: "wine-bars",
        label: "Wine Bars",
        subjects: [
        { caption: "Stars [East Village, NYC]" },
        { caption: "Sauced [Williamsburg & Lower East Side, NYC]" },
        ],
      },
    ],
  },
  {
    hotspotId: "skincare-routine",
    intro: "Placeholder intro -- replace with 1-2 real sentences about skincare routine.",
    sections: [
      {
        id: "routine",
        label: "Routine",
        subjects: [
        { caption: "POLA cleanser", link: "https://www.pola.com/products/1232/" },
        { caption: "La Mer Revitalizing Mist", link: "https://www.cremedelamer.com/product/20180/26248/face/cleansers-and-toners/the-revitalizing-mist?srsltid=AfmBOorOjuHFl1jSfog4EZH7ivcewjmxE7-TuHnEo46LZPkoR2BfSS7f" },
        { caption: "La Mer Treatment Lotion", link: "https://www.cremedelamer.com/product/11484/99912/prep/the-treatment-lotion?gclsrc=aw.ds&gad_source=1&gad_campaignid=21365407172&gbraid=0AAAAADSEbdYndufhNzILrFxxpE-d7z5wk&gclid=Cj0KCQjwzY7VBhDwARIsAFtPvBTmXD96TeqylUxjq_kTn1rwF3ZYBkAdL8oYTPjiH8gXPggl3xfkGAkaAjRXEALw_wcB#/sku/147757" },
        { caption: "La Mer Eye Concentrate", link: "https://www.cremedelamer.com/product/20652/74983/face/eye-treatments/the-eye-concentrate?_gl=1*10w7zav*_up*MQ..*_gs*MQ..&gclid=Cj0KCQjwzY7VBhDwARIsAFtPvBTmXD96TeqylUxjq_kTn1rwF3ZYBkAdL8oYTPjiH8gXPggl3xfkGAkaAjRXEALw_wcB&gclsrc=aw.ds&gbraid=0AAAAADSEbdYndufhNzILrFxxpE-d7z5wk#/sku/115246" },
        { caption: "La Mer Renewal Oil", link: "https://www.cremedelamer.com/product/32970/120231/face/face-oils/the-renewal-oil?_gl=1*b0d2am*_up*MQ" },
        { caption: "Creme de La Mer", link: "https://www.cremedelamer.com/product/5834/12343/face/moisturizers/creme-de-la-mer?_gl=1*1uoahs6*_up*MQ" },
        { caption: "La Mer Hand Treatment", link: "https://www.cremedelamer.com/product/5819/12350/body/the-hand-treatment?_gl=1*1uoahs6*_up*MQ" },
        { caption: "La Mer Lip Balm", link: "https://www.cremedelamer.com/product/24131/64925/face/lip-care/the-lip-balm?_gl=1*1fqd2h9*_up*MQ" },
        ],
      },
    ],
  },
  {
    hotspotId: "book-collection",
    intro: "Placeholder intro -- replace with 1-2 real sentences about book collection.",
    sections: [
      {
        id: "routine",
        label: "Routine",
        subjects: [
        { caption: "The Education of an Idealist by Samantha Power" },
        { caption: "The Snakehead by Patrick Radden Keefe" },
        { caption: "Broken Code by Jeff Horwitz" },
        ],
      },
    ],
  },
  {
    hotspotId: "shoe-closet",
    intro: "Placeholder intro -- replace with 1-2 real sentences about shoe closet.",
    sections: [
      {
        id: "routine",
        label: "Routine",
        subjects: [
        { caption: "Amina Muaddi Begum Slings" },
        { caption: "Loro Piana Joan Loafers" },
        { caption: "Onitsuka Tiger Mexico Beige Grass Green" },
        { caption: "Hermas Oran Sandal in Gold" },
        { caption: "Khaite Davis Knee Boots" },
        { caption: "Dr. Martens 1460 Pascal Virginia Leather" },
        ],
      },
    ],
  },
];

export function getExpansion(hotspotId: string): HotspotExpansion | undefined {
  return hotspotExpansions.find((e) => e.hotspotId === hotspotId);
}
